### ISSUE TITLE
Font files missing on live site

### ISSUE THREAD

**Issue by mrbohnke** [harrewarre/ThroneFeed#1]
Hi! I didn't know how to best contact you, so I'll try here :)
First of all, thank you for ThroneFeed, since it is so cool.
Looks like your live version of ThroneFeed is missing some files (woff & woff2) on Fonts folder and, I suspect, this could be the reason why it is not showing the proper font on the OBS browser plugin:

network activity screenshot 
![thronefeed screenshot](http://f.cl.ly/items/3T2u0e2s1m3g3L04460w/Captura%20de%20pantalla%202016-02-24%20a%20las%2013.28.09.png)
obs widget screenshot
![obs screenshot](https://s3.amazonaws.com/f.cl.ly/items/1O3i010s0d2C1E0o2V3o/Captura%20de%20pantalla%202016-02-24%20a%20las%2013.32.54.png?v=e813a931)

Thank you for your time,
Cheers!

**Comment by harrewarre** [comment]
Hey! thanks for the heads-up. I pushed a small update to the site that should fix the fonts not loading. Let me know if something is still not right.

**Comment by mrbohnke** [comment]
That was fast, thank you! sadly, looks like this was not the problem after all… somehow, the plugin doesn't like fonts used this way, but successfully uses the SAME FONT when it is hosted by google (using `@import url(https://fonts.googleapis.com/css?family=Press+Start+2P);` on style). so weird!

**Comment by harrewarre** [comment]
Hmm, that's strange indeed. I think I'll switch out the font I have now for the one hosted by google so that the problem is fixed all together.
Thanks for testing the google font!

**Comment by mrbohnke** [comment]
Thank you!

**Comment by harrewarre** [comment]
Switched the fonts, should be all good now :-)

**Comment by mrbohnke** [comment]
Like a charm, now! ^_^
![](https://s3.amazonaws.com/f.cl.ly/items/0f0W310m1J1C0i3q1q0F/Captura%20de%20pantalla%202016-02-24%20a%20las%2014.38.40.png?v=ca2e092c)
Again, thank you!
